#back
commands.teleport_commands.back.error = "Error Teleporting!"
commands.teleport_commands.back.same = "Already Back"
commands.teleport_commands.back.noLocation = "No Location Found!"

#home
commands.teleport_commands.home.set = "Home Set"
commands.teleport_commands.home.setError = "Error Setting Home!"
commands.teleport_commands.home.go = "Going Home"
commands.teleport_commands.home.goError = "Error Going Home!"
commands.teleport_commands.home.goSame = "Already Home"
commands.teleport_commands.home.delete = "Home Deleted"
commands.teleport_commands.home.deleteError = "Error Deleting Home!"
commands.teleport_commands.home.rename = "Home Renamed"
commands.teleport_commands.home.renameError = "Error Renaming Home!"
commands.teleport_commands.home.renameExists = "That Name Already Exists!"
commands.teleport_commands.home.default = "Default Home Set"
commands.teleport_commands.home.defaultError = "Error Changing Default Home!"
commands.teleport_commands.home.defaultSame = "Home is already set as default!"
commands.teleport_commands.home.notFound = "Home Not Found!"
commands.teleport_commands.home.exists = "Home Already Exists!"
commands.teleport_commands.home.homeless = "You Have No Homes!"

# homes
commands.teleport_commands.homes.error = "Error Getting Homes!"
commands.teleport_commands.homes.homes = "Homes: \n"
commands.teleport_commands.homes.default = " (Default)"
commands.teleport_commands.homes.tp = " [Tp]"
commands.teleport_commands.homes.rename = " [Rename]"
commands.teleport_commands.homes.delete = " [Delete]\n"

# tpa
commands.teleport_commands.tpa.self = "Well, that was easy"
commands.teleport_commands.tpa.received = "Tpa%s Request Received From "
commands.teleport_commands.tpa.sent = "Tpa%s Request Sent to "
commands.teleport_commands.tpa.accept = "\n[Accept]"
commands.teleport_commands.tpa.deny = " [Deny]"
commands.teleport_commands.tpa.expired = "Tpa%s Request Expired"
commands.teleport_commands.tpa.notFound = "No Requests found!"
commands.teleport_commands.tpa.accepted = "Request Accepted"
commands.teleport_commands.tpa.denied = "Request Denied"

# common
commands.teleport_commands.common.teleport = "Teleporting"